import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import axios from "axios";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [movies, setMovie] = useState([
    {
      title: "",
      category: "",
      description: "",
      type_of_content: "",
      director: "",
      actors: "",
      path: "",
    },
  ]);

  const [shows, setShow] = useState([
    {
      title: "",
      category: "",
      description: "",
      type_of_content: "",
      director: "",
      actors: "",
      path: "",
    },
  ]);

  async function gettingData() {
    const response = await axios(`http://localhost:5000/movies`);
    const data = await response.data;
    console.log(data);

    setMovie(data);
  }

  async function gettingShows() {
    const response = await axios(`http://localhost:5000/shows`);
    const data = await response.data;
    console.log(data);

    setShow(data);
  }

  useEffect(() => {
    gettingData();
    gettingShows();
  }, []);

  return (
    <>
      <Head>
        <title>Home Streaming Service</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="_abd">
          <h1>Random Selection</h1>
          <div className="video-cards"></div>
        </div>
        <div className="_abd">
          <h1>Movies</h1>
          <div className="video-cards">
            {movies.map((details) => (
              <div key={details.id} className="card">
                <div className="container">
                  <h4>
                    <b>{details.title}</b>
                  </h4>
                  <p>{details.category}</p>
                  <Link
                    href={`/watch/movies/${encodeURIComponent(details.title)}`}
                  >
                    See Movie
                  </Link>
                </div>
              </div>
            ))}
          </div>
        </div>
        <div className="_abd">
          <h1>Shows</h1>
          <div className="video-cards">
            {shows.map((details) => (
              <div key={details.id} className="card">
                <div className="container">
                  <h4>
                    <b>{details.title}</b>
                  </h4>
                  <p>{details.category}</p>
                  <Link
                    href={`/watch/shows/${encodeURIComponent(details.title)}`}
                  >
                    See Show
                  </Link>
                </div>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
