import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Streaming Service</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="_abd">
          <h1>Random Selection</h1>
          <div className="video-cards">
            <div class="card">
              <div class="container">
                <h4>
                  <b>Money Ball</b>
                </h4>
                <p>Description</p>
              </div>
            </div>
            <div class="card">
              <div class="container">
                <h4>
                  <b>John Doe</b>
                </h4>
                <p>Architect & Engineer</p>
              </div>
            </div>
          </div>
        </div>
        <div className="_abd">
          <h1>Movies</h1>
          <div className="video-cards">
            <div class="card">
              <div class="container">
                <h4>
                  <b>Money Ball</b>
                </h4>
                <p>Description</p>
              </div>
            </div>
            <div class="card">
              <div class="container">
                <h4>
                  <b>John Doe</b>
                </h4>
                <p>Architect & Engineer</p>
              </div>
            </div>
            <div class="card">
              <div class="container">
                <h4>
                  <b>John Doe</b>
                </h4>
                <p>Architect & Engineer</p>
              </div>
            </div>
            <div class="card">
              <div class="container">
                <h4>
                  <b>John Doe</b>
                </h4>
                <p>Architect & Engineer</p>
              </div>
            </div>
            <div class="card">
              <div class="container">
                <h4>
                  <b>John Doe</b>
                </h4>
                <p>Architect & Engineer</p>
              </div>
            </div>
            <div class="card">
              <div class="container">
                <h4>
                  <b>John Doe</b>
                </h4>
                <p>Architect & Engineer</p>
              </div>
            </div>
            <div class="card">
              <div class="container">
                <h4>
                  <b>John Doe</b>
                </h4>
                <p>Architect & Engineer</p>
              </div>
            </div>
          </div>
        </div>
        <div className="_abd">
          <h1>Shows</h1>
          <div className="video-cards">
            <div class="card">
              <div class="container">
                <h4>
                  <b>Money Ball</b>
                </h4>
                <p>Description</p>
              </div>
            </div>
            <div class="card">
              <div class="container">
                <h4>
                  <b>John Doe</b>
                </h4>
                <p>Architect & Engineer</p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
