import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import axios from "axios";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [datas, setData] = useState([
    {
      title: "",
      category: "",
      description: "",
      type_of_content: "",
      director: "",
      actors: "",
      path: "",
    },
  ]);

  async function gettingData() {
    const response = await axios(`http://localhost:5000/content`);
    const data = await response.data;
    // const results = data;
    console.log(data);

    setData(data);
  }

  // datas.map((d) => console.log(d.title));

  // for(let i = 0; i < data.length; i++) {
  //   console.log(data[i].title);
  // }

  useEffect(() => {
    gettingData();
  }, []);

  return (
    <>
      <Head>
        <title>Home Streaming Service</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="_abd">
          <h1>Random Selection</h1>
          <div className="video-cards">
            <div className="card">
              <div className="container">
                <h4>
                  <b>Money Ball</b>
                </h4>
                <p>Description</p>
              </div>
            </div>
            <div className="card">
              <div className="container">
                <h4>
                  <b>John Doe</b>
                </h4>
                <p>Architect & Engineer</p>
              </div>
            </div>
          </div>
        </div>
        <div className="_abd">
          <h1>Movies</h1>
          <div className="video-cards">
            {datas.map((details) => (
              <div key={details.id} className="card">
                <div className="container">
                  <h4>
                    <b>{details.title}</b>
                  </h4>
                  <p>{details.category}</p>
                  <Link href={`http://localhost:3000/watch/${details.title}`}>See Movie</Link>
                </div>
              </div>
            ))}
          </div>
        </div>
        <div className="_abd">
          <h1>Shows</h1>
          <div className="video-cards">
            <div className="card">
              <div className="container">
                <h4>
                  <b>Money Ball</b>
                </h4>
                <p>Description</p>
              </div>
            </div>
            <div className="card">
              <div className="container">
                <h4>
                  <b>John Doe</b>
                </h4>
                <p>Architect & Engineer</p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
